image:
  file: .devcontainer/Dockerfile
vscode:
  extensions:
    - bazelbuild.vscode-bazel
    - jeff-hykin.better-cpp-syntax
    - cschlosser.doxdocgen
    - github.vscode-pull-request-github
    - llvm-vs-code-extensions.vscode-clangd
    - eamodio.gitlens
    - xaver.clang-format
    - actboy168.tasks
    - vscode-icons-team.vscode-icons
    - matepek.vscode-catch2-test-adapter
    - zxh404.vscode-proto3
    - redhat.vscode-xml
    - redhat.vscode-yaml
