image: astefan93/cpp:latest
tasks:
    - init: conan install **/*/conanfile.txt --output-folder=build --build=missing --profile:build=conan/gcc_debug --profile:host=conan/gcc_debug
    - command: bazel build --config clang_debug ... && bazel run @hedron_compile_commands//:refresh_all -- --config=clang_debug && bazel build --config=iwyu ...

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
# enable for all branches in this repo (defaults to false)
        branches: true
# enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
# enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
# add a "Review in Gitpod" button to pull requests (defaults to false)
        addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
        addLabel: prebuilt-in-gitpod
vscode:
    extensions:
        - bazelbuild.vscode-bazel
        - jeff-hykin.better-cpp-syntax
        - cschlosser.doxdocgen
        - github.vscode-pull-request-github
        - llvm-vs-code-extensions.vscode-clangd
        - eamodio.gitlens
        - xaver.clang-format
        - actboy168.tasks
        - vscode-icons-team.vscode-icons
        - matepek.vscode-catch2-test-adapter
        - zxh404.vscode-proto3
        - redhat.vscode-xml
        - redhat.vscode-yaml
        - cschleiden.vscode-github-actions
        - ms-python.python
        - JFrog.jfrog-vscode-extension
        - ms-vscode.cmake-tools
        - KylinIDETeam.cmake-intellisence
        - twxs.cmake
