image:
  file: .devcontainer/Dockerfile
tasks:
  - command: |
    bazel build --config release ... && bazel run @hedron_compile_commands//:refresh_all -- --config=release

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - bazelbuild.vscode-bazel
    - jeff-hykin.better-cpp-syntax
    - cschlosser.doxdocgen
    - github.vscode-pull-request-github
    - llvm-vs-code-extensions.vscode-clangd
    - eamodio.gitlens
    - xaver.clang-format
    - actboy168.tasks
    - vscode-icons-team.vscode-icons
    - matepek.vscode-catch2-test-adapter
    - zxh404.vscode-proto3
    - redhat.vscode-xml
    - redhat.vscode-yaml
