image:
  file: .devcontainer/Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - ms-vscode.cmake-tools
    - jeff-hykin.better-cpp-syntax
    - cschlosser.doxdocgen
    - github.vscode-pull-request-github
    - llvm-vs-code-extensions.vscode-clangd
    - eamodio.gitlens
    - xaver.clang-format
    - vscode-icons-team.vscode-icons
    - matepek.vscode-catch2-test-adapter
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - cheshirekow.cmake-format
    - jfrog.jfrog-vscode-extension
    - twxs.cmake
