name: Auto-Merge
on:
  pull_request_target

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'renovate[bot]'
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        merge-method: "SQUASH"
