# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: ["**"]
  # schedule:
  #   - cron: "45 8 * * 4"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45.0.1
        with:
          files: .devcontainer/Dockerfile
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: docker build -t local -f .devcontainer/Dockerfile .
      - name: Tag docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: docker image tag local astefan93/cpp:latest
      - name: Push docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: docker push astefan93/cpp:latest

  UbuntuLatestCMake:
    runs-on: ubuntu-latest
    needs: BuildImage
    strategy:
      matrix:
        compiler: [clang]
        configuration: [Debug, Release]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run container
        run: docker run --name localContainer -idt --volume $PWD:/workspace/CPPTest astefan93/cpp:latest
      - name: Configure CMake
        run: docker exec -w/workspace/CPPTest localContainer sudo cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=${{ matrix.configuration }} -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/${{ matrix.compiler }} -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/${{ matrix.compiler }}++ -S/workspace/CPPTest -B/workspace/CPPTest/build -G "Unix Makefiles"
      - name: Build CMake
        run: docker exec -w/workspace/CPPTest localContainer sudo cmake --build /workspace/CPPTest/build  --config ${{ matrix.configuration }} --target all -j 18 --
      - name: Run CMake tests
        run: docker exec -w/workspace/CPPTest localContainer sudo ctest -j18 -T test --test-dir build/src --no-tests=error -C ${{ matrix.configuration }} -V
      - name: Stop container
        run: docker stop localContainer
